### ISSUE TITLE
Victory condition without flags. Mineless cells.

### ISSUE THREAD

**Issue by BillKek** [tsoding/mine#2]
To comply with the regulations of the pro-players should be added an additional ability to win without the use of flags.  That is, when all mineless cells are open.

For example in the following way:
https://github.com/BillKek/mine_win32/commit/26ea1f74b5cfb8eb89efda723cf8b3bf0002804b
or in a cleaner way without copy-pasting.

**Comment by rexim** [comment]
Fixed 1d5bf73e6ad6921067abd3aef188ef565f8a5bb1

Please let me know if this is sufficient.
